### ISSUE TITLE
Research network usage

### ISSUE THREAD

**Issue by chonny24** [chonny24/cloud-robotics#37]
Right now we just have an arbitrary network threshold for switching location. We should do some research about what it takes to run roscore on a master server, as well as communicating over the topic.

Some things of note:
* are all topics being broadcasted over the network regardless of who is consuming them?
* does everything have to redirect through the roscore master?
* how much bandwidth is being used just to run the roscore master?
* how much bandwidth is being used to run amcl on the server?

**Comment by EvanSchallerer** [comment]
Most of this we don't care about. We now need to look at the consequences of larger state syncs (related: #49 ), as well as actual values for network thresholds (related: #50)
