### ISSUE TITLE
Use robot as ROS master, point server AMCL at robot

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#47]
Set ROS master as the local robot. Set each server-side AMCL to point at its robot's master.

**Comment by EvanSchallerer** [comment]
Hopefully, this will resolve #32.

**Comment by EvanSchallerer** [comment]
Nodes died when this was attempted and the connection was killed, as each node was trying to communicate over wifi.

What if:
- We only set ROS_MASTER_URI on
 - diagnostics.py (or mockdiagnostics.py),  on the robot
 - roscore, on the robot 
 - (obviously) the server

This way, none of the robot's nodes would lose connection to each other. If the connection is lost completely, we would need to have a failsafe that switches back to the local amcl, as the diagnostics node would not be able to communicate to switch back to the client before the connection is lost. 

This solution may mean that there are multiple masters, which might be a problem.

**Comment by chonny24** [comment]
I'm worried this will result in nodes not hearing each other. If one node has the master "localhost", and another has the master "192.168.1.xx", I dont think they will know the other exists.

**Comment by EvanSchallerer** [comment]
I agree. We should test it though, there may be a way around that.

**Comment by coanj** [comment]
Poster from another research project mentioning how they accomplished multi-master connections:
https://www.ri.cmu.edu/education/McEachernRISSposter.pdf

Another possible solution that might require even less setup:
http://wiki.ros.org/multimaster_fkie

**Comment by EvanSchallerer** [comment]
Also may be helpful: http://wiki.ros.org/adhoc_communication

**Comment by EvanSchallerer** [comment]
When we tested this, we turned off the wifi on my laptop, which may have disabled some networking. We should try blocking my laptop's wifi, and see if that changes anything.
