### ISSUE TITLE
Network and Processor Thresholds

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#50]
Determine actual threshold values for the network and processor. Related to #57

**Comment by chonny24** [comment]
Leave this to the user?

**Comment by coanj** [comment]
I would think that would be best since it might depend on multiple things, like the amount of information being sent.

**Comment by EvanSchallerer** [comment]
Made a wiki page describing how to change bandwidth threshold. They can also figure out CPU threshold from that if they care. -Jon
