### ISSUE TITLE
Delete unnecessary branches 

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#52]
- [ ] The `coanj` branch can probably be deleted because I must have accidentally merged it with amcl_switch or something. Can someone verify this, and if so, delete it?

- [ ] The `amcl_switch` branch may have some useful code in it, but not much. Don't delete until we have verified that we have everything that we want out of it.

**Comment by chonny24** [comment]
coanj can probably be deleted

amcl_switch should be left until we merge demo into master

**Comment by coanj** [comment]
I deleted the coanj branch

**Comment by chonny24** [comment]
TOAST
