### ISSUE TITLE
Research throttling CPU/Network on PR2

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#57]
Need to test limits of our project: Network especially, maybe CPU as well.
We'll probably want to do this on the robot instead of just simulations?

This probably shouldn't be difficult, James was using tools for this.

**Comment by coanj** [comment]
I was only using my connection through a VM, but I'm unable to make that work for anymore for some reason. It would probably be better if, when we get a chance to use this on the robot, we do our testing there for limitations. Just a thought at least.

**Comment by coanj** [comment]
**Wondershaper**
A tool to limit bandwidth of a particular interface.

$ sudo wondershaper {interface} {down} {up}
the {down} and {up} are bandwidth in kilobits. 

So for example if you want to limit the bandwidth of interface eth1 to 256kbps uplink and 128kbps downlink:
$ sudo wondershaper eth1 256 128

To clear the limit,
$ sudo wondershaper clear eth1

**Stress**
A tool to stress the CPU for testing (this is the one I used in my demos)

Example to stress 2 cores for 60 seconds:
$ stress --cpu 2 --timeout 60
