### ISSUE TITLE
Research Indigo vs. Hydro(?) changes

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#58]
Could possibly test this on one of the robotics lab computers. Look into this.

- Do we actually need to switch?
    - Ubuntu 12.0<?>, Hydro (or was it Groovy?) 
- Has anything actually changed?

**Comment by chonny24** [comment]
AMCL relies on some different messages unfortunately, so it cant just plug ours in on Hydro. We have to make some modifications
